### PR TITLE
Solidity: `mulmod` and `addmod` builtins

### PR DESCRIPTION
**Pull request by xermicus**
This hash function is used in tornado and I thought it would provide a good benchmark case:
```solidity
contract NativeHasher { 
    function MiMCSponge(uint256 xL_in,uint256 xR_in) external pure returns(uint256,uint256) { 
        uint n = 220; 
        bytes32 ci = 0x0fbe43c36a80e36d7c7c584d4f8f3759fb51f0d66065d8a227b688d12488c5d4;
        uint q = 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001;
        uint xL = xL_in;
        uint xR = xR_in;
        uint t=xL;
        uint b=mulmod(t, t, q);
        uint c=mulmod(b, b, q);
        uint d=mulmod(c, t, q);
        xR=addmod(xR, d, q);
        
        for(uint i = 0; i < n-1; i++){
            if (i<n-2 && i!=0){
                ci = keccak256(abi.encodePacked(ci));
            }
            else if(i==n-2)
            {
                ci = bytes32(0);
            }
            (xL, xR)=(xR, xL);
            t = addmod(uint(ci), xL, q);
            
            b = mulmod(t, t, q);
            c = mulmod(b, b, q);
            d = mulmod(c, t, q);
            xR = addmod(xR, d, q);
        }
		print("{:x}".format(xL));
		print("{:x}".format(xR));
        return (xL, xR);
    } 

} 
```

 The contract that the tornado protocol uses in production is actually hand-crafted EVM bytecode because the Solidity version coming with this PR is too slow / too expensive to. But there is this Solidity version floating around too.

Discovered because with Solang (Wasm), that hashing contract is [100x slower than EVM](https://github.com/hyperledger/solang/issues/1361) (!!). On my machine, RISC-V 32bit speeds up 10x already, wondering how it will be with a 64bit RISC-V target.

The overall performance of this contract depends on the the performance of the `mulmod` and `addmod` builtins. This PR contains an isolated for them.

### CODE REVIEW

**Review by ascjones — APPROVED** [review]
Nice!

**Comment by ascjones** [comment]
Although the description talks all about `MiMCSponge` which doesn't appear in the PR, just the arithmetic

**Comment by ascjones** [comment]
Oh I see, the key is the last sentence:

> The overall performance of this contract depends on the the performance of the mulmod and addmod builtins. This PR contains an isolated for them.

**Comment by xermicus** [comment]
Exactly, I think that everything besides the `addmod` and `mulmod` builtins in the hasher contract is basically just irrelevant ballast in regards to the benchmark :)

**Pull request merged**
